server:
  port : 8088
spring:
  application:
    name : API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173'
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST



eureka:
  instance:
    prefer-ip-address : true
  client:
    fetchRegistry : true
    registerWithEureka : true
    serviceUrl :
      defaultZone : http://localhost:8761/eureka